
---
title: 'Tipología: PRA1'
author: "Autor: Iván López-Baltasar Benito | David Quiles Gómez"
date: "Abril 2019"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
  pdf_document:
    highlight: zenburn
    toc: yes
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

******
******
# Presentación
Analisis del dataset obtenido mediante webscraping

# Procesos de limpieza del juego de datos

Primer contacto con el juego de datos, visualizamos su estructura.  

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Cargamos los paquetes R que vamos a usar
library(ggplot2)
library(dplyr)

# cargamos el dataset
cochesDS <- read.csv('FindMyCar.csv',stringsAsFactors = FALSE,encoding = "UTF-8")

names(cochesDS) <- c("Modelo","Link","Precio","A_Matriculacion","Kms","Combustible","Potencia","Puertas","Cambio","Provincia")

filas=dim(cochesDS)[1]

# Primera Verificacion de la estructura del juego de datos
str(cochesDS)

# limpiamos algunos atributos
cochesDS$A_Matriculacion <- as.numeric(substr(cochesDS$A_Matriculacion,5,8))
cochesDS$Precio = as.numeric(gsub("[\\€,]", "", cochesDS$Precio))*1000
cochesDS$Kms = as.numeric(gsub("[\\kms,]", "", cochesDS$Kms))*1000
cochesDS$Potencia = as.numeric(gsub("[\\cv,]", "", cochesDS$Potencia))
cochesDS$Puertas = as.numeric(gsub("[\\puertas,]", "", cochesDS$Puertas))

# Discretizamos las variables cambio y combustible
cols<-c("Cambio","Combustible")
for (i in cols){
  cochesDS[,i] <- as.factor(cochesDS[,i])
}

```
# Analisis visual de los datos

```{r echo=TRUE, message=FALSE, warning=FALSE}
str(cochesDS)
summary(cochesDS)
```
